#!/bin/sh
# List system tools and pass selection to fuzzel
choice=$(printf "%s\n" \
    "󰂯 Bluetooth (blueman-manager)" \
    "󰖩 Network (nm-connection-editor)" \
    "󰓃 Sound (pavucontrol)" \
    "󰍛 Display (wdisplays)" \
    " CPU Mode" \
    "󰘓 Htop (htop)" \
    "󰹑 Nvtop (nvtop)" \
    | fuzzel --dmenu --prompt="System Tools  ")

# Launch the selected tool
case "$choice" in
    *Bluetooth*) blueman-manager & ;;
    *Network*) nm-connection-editor & ;;
    *Sound*) pavucontrol & ;;
    *Display*) wdisplays & ;;  # Alternative: wlr-randr, kanshi
    *CPU*) ~/.config/fuzzel/scripts/cpu-mode ;;
    *Nvtop*) alacritty --title "st-nvtop" -e nvtop & ;;
    *Htop*) alacritty --title "st-htop" -e htop & ;;

esac
